services:
  peas:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      BLOBS_PATH: /app/blobs
      ACCESS_KEY: developer
      SECRET_KEY: developer
    volumes:
      - peas-blobs:/app/blobs

volumes:
  peas-blobs:
