// Auto-generated by fetch-gen
import type { FetchClient, FetchResponse } from '@fgrzl/fetch';
import { buildQueryParams } from '@fgrzl/fetch';

/**
 * Creates an API adapter with typed methods for all OpenAPI operations.
 *
 * @param client - The FetchClient instance to use for HTTP requests
 * @returns An object with typed methods for each API operation
 *
 * @example
 * ```typescript
 * import { createAdapter } from './generated';
 * import client from '@fgrzl/fetch';
 *
 * client.setBaseUrl('https://api.example.com');
 * const api = createAdapter(client);
 *
 * const response = await api.getUsers();
 * if (response.ok) {
 *   console.log(response.data);
 * }
 * ```
 */
export function createAdapter(client: FetchClient): {
  /**
   * Create admin session
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SuccessResponse>
   */
  loginAdminSession: (
    body: AdminLoginRequest,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<SuccessResponse>>;
  /**
   * Clear admin session
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SuccessResponse>
   */
  logoutAdminSession: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<SuccessResponse>>;
  /**
   * Create bucket
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<BucketDetails>
   */
  createBucket: (
    body: CreateBucketRequest,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<BucketDetails>>;
  /**
   * List buckets
   *
   * @param query - Query parameters
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListBucketsResponse>
   */
  listBuckets: (
    query?: { next?: string; limit?: number; search?: string },
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<ListBucketsResponse>>;
  /**
   * Delete bucket
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
  deleteBucket: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<boolean>>;
  /**
   * Get bucket
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<BucketDetails>
   */
  getBucket: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<BucketDetails>>;
  /**
   * List objects in a bucket
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListObjectsResponse>
   */
  listObjects: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<ListObjectsResponse>>;
  /**
   * Delete object
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
  deleteObject: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<boolean>>;
  /**
   * Get object metadata
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ObjectMetadata>
   */
  getObjectMetadata: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<ObjectMetadata>>;
  /**
   * Download object content
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<any>
   */
  downloadObjectContent: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<any>>;
  /**
   * Create or replace object content
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ObjectMetadata>
   */
  putObjectContent: (
    body: any,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<ObjectMetadata>>;
  /**
   * Get object tags
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<TagsResponse>
   */
  getObjectTags: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<TagsResponse>>;
  /**
   * Replace object tags
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<TagsResponse>
   */
  putObjectTags: (
    body: TagsRequest,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<TagsResponse>>;
  /**
   * List object versions
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListVersionsResponse>
   */
  listObjectVersions: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<ListVersionsResponse>>;
  /**
   * Get bucket versioning status
   *
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<VersioningStatus>
   */
  getBucketVersioning: (options?: {
    signal?: AbortSignal;
    timeout?: number;
    operationId?: string;
  }) => Promise<FetchResponse<VersioningStatus>>;
  /**
   * Set bucket versioning status
   *
   * @param body - Request body
   * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<VersioningStatus>
   */
  setBucketVersioning: (
    body: VersioningStatus,
    options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
  ) => Promise<FetchResponse<VersioningStatus>>;
} {
  return {
    loginAdminSession: (
      body: AdminLoginRequest,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<SuccessResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'loginAdminSession',
      };
      return client.post(`/auth/login`, body, undefined, finalOptions);
    },
    logoutAdminSession: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<SuccessResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'logoutAdminSession',
      };
      return client.post(`/auth/logout`, undefined, undefined, finalOptions);
    },
    createBucket: (
      body: CreateBucketRequest,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<BucketDetails>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'createBucket',
      };
      return client.post(`/buckets`, body, undefined, finalOptions);
    },
    listBuckets: (
      query?: { next?: string; limit?: number; search?: string },
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<ListBucketsResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'listBuckets',
      };
      const queryString = query ? buildQueryParams(query) : '';
      const url = `/buckets` + (queryString ? '?' + queryString : '');
      return client.get(url, undefined, finalOptions);
    },
    deleteBucket: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<boolean>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'deleteBucket',
      };
      return client.del(`/buckets/{bucketName}`, undefined, finalOptions);
    },
    getBucket: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<BucketDetails>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'getBucket',
      };
      return client.get(`/buckets/{bucketName}`, undefined, finalOptions);
    },
    listObjects: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<ListObjectsResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'listObjects',
      };
      return client.get(
        `/buckets/{bucketName}/objects`,
        undefined,
        finalOptions
      );
    },
    deleteObject: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<boolean>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'deleteObject',
      };
      return client.del(
        `/buckets/{bucketName}/objects/{objectKey}`,
        undefined,
        finalOptions
      );
    },
    getObjectMetadata: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<ObjectMetadata>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'getObjectMetadata',
      };
      return client.get(
        `/buckets/{bucketName}/objects/{objectKey}`,
        undefined,
        finalOptions
      );
    },
    downloadObjectContent: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<any>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'downloadObjectContent',
      };
      return client.get(
        `/buckets/{bucketName}/objects/{objectKey}/content`,
        undefined,
        finalOptions
      );
    },
    putObjectContent: (
      body: any,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<ObjectMetadata>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'putObjectContent',
      };
      return client.put(
        `/buckets/{bucketName}/objects/{objectKey}/content`,
        body,
        undefined,
        finalOptions
      );
    },
    getObjectTags: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<TagsResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'getObjectTags',
      };
      return client.get(
        `/buckets/{bucketName}/objects/{objectKey}/tags`,
        undefined,
        finalOptions
      );
    },
    putObjectTags: (
      body: TagsRequest,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<TagsResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'putObjectTags',
      };
      return client.put(
        `/buckets/{bucketName}/objects/{objectKey}/tags`,
        body,
        undefined,
        finalOptions
      );
    },
    listObjectVersions: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<ListVersionsResponse>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'listObjectVersions',
      };
      return client.get(
        `/buckets/{bucketName}/objects/{objectKey}/versions`,
        undefined,
        finalOptions
      );
    },
    getBucketVersioning: (options?: {
      signal?: AbortSignal;
      timeout?: number;
      operationId?: string;
    }): Promise<FetchResponse<VersioningStatus>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'getBucketVersioning',
      };
      return client.get(
        `/buckets/{bucketName}/versioning`,
        undefined,
        finalOptions
      );
    },
    setBucketVersioning: (
      body: VersioningStatus,
      options?: { signal?: AbortSignal; timeout?: number; operationId?: string }
    ): Promise<FetchResponse<VersioningStatus>> => {
      const finalOptions = {
        ...options,
        operationId: options?.operationId ?? 'setBucketVersioning',
      };
      return client.put(
        `/buckets/{bucketName}/versioning`,
        body,
        undefined,
        finalOptions
      );
    },
  };
}

/** AdminLoginRequest schema */
export type AdminLoginRequest = { password: string; username: string };

/** BucketDetails schema */
export type BucketDetails = BucketInfo;

/** BucketInfo schema */
export type BucketInfo = {
  created_at: string;
  name: string;
  versioning_enabled: boolean;
};

/** CreateBucketRequest schema */
export type CreateBucketRequest = { name: string };

/** ErrorResponse schema */
export type ErrorResponse = {
  code: string;
  details: string | null;
  error: string;
};

/** ListBucketsResponse schema */
export type ListBucketsResponse = {
  items: Array<BucketInfo>;
  next: string | null;
};

/** ListObjectsResponse schema */
export type ListObjectsResponse = {
  items: Array<ObjectInfo>;
  next: string | null;
};

/** ListVersionsResponse schema */
export type ListVersionsResponse = {
  items: Array<ObjectVersionInfo>;
  next: string | null;
};

/** ObjectInfo schema */
export type ObjectInfo = {
  content_type: string | null;
  etag: string;
  key: string;
  last_modified: string;
  size: number;
  storage_class: string;
};

/** ObjectMetadata schema */
export type ObjectMetadata = {
  content_type: string | null;
  etag: string;
  key: string;
  last_modified: string;
  metadata: Record<string, string>;
  size: number;
  storage_class: string;
  version_id: string | null;
};

/** ObjectVersionInfo schema */
export type ObjectVersionInfo = {
  etag: string;
  is_latest: boolean;
  key: string;
  last_modified: string;
  size: number;
  version_id: string;
};

/** SuccessResponse schema */
export type SuccessResponse = { success: boolean };

/** TagsRequest schema */
export type TagsRequest = { tags: Record<string, string> };

/** TagsResponse schema */
export type TagsResponse = { tags: Record<string, string> };

/** VersioningStatus schema */
export type VersioningStatus = { enabled: boolean };
