// Auto-generated by fetch-gen
import type { FetchClient, FetchResponse } from '@fgrzl/fetch';
import { buildQueryParams } from '@fgrzl/fetch';

/**
 * Creates an API adapter with typed methods for all OpenAPI operations.
 *
 * @param client - The FetchClient instance to use for HTTP requests
 * @returns An object with typed methods for each API operation
 *
 * @example
 * ```typescript
 * import { createAdapter } from './generated';
 * import client from '@fgrzl/fetch';
 *
 * client.setBaseUrl('https://api.example.com');
 * const api = createAdapter(client);
 *
 * const response = await api.getUsers();
 * if (response.ok) {
 *   console.log(response.data);
 * }
 * ```
 */
export function createAdapter(client: FetchClient): {
  /**
   * Create admin session
   *
   * @param body - Request body
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SuccessResponse>
   */
	loginAdminSession: (body: AdminLoginRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<SuccessResponse>>;
  /**
   * Clear admin session
   *
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<SuccessResponse>
   */
	logoutAdminSession: (options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<SuccessResponse>>;
  /**
   * Get admin session status
   *
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<AdminSessionResponse>
   */
	getAdminSession: (options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<AdminSessionResponse>>;
  /**
   * Create bucket
   *
   * @param body - Request body
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<BucketDetails>
   */
	createBucket: (body: CreateBucketRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<BucketDetails>>;
  /**
   * List buckets
   *
   * @param query - Query parameters
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListBucketsResponse>
   */
	listBuckets: (query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<ListBucketsResponse>>;
  /**
   * Delete bucket
   *
   * @param bucketName - Bucket name.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
	deleteBucket: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<boolean>>;
  /**
   * Get bucket
   *
   * @param bucketName - Bucket name.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<BucketDetails>
   */
	getBucket: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<BucketDetails>>;
  /**
   * List objects in a bucket
   *
   * @param bucketName - Bucket name.
   * @param query - Query parameters
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListObjectsResponse>
   */
	listObjects: (bucketName: string, query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<ListObjectsResponse>>;
  /**
   * Delete object
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<boolean>
   */
	deleteObject: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<boolean>>;
  /**
   * Get object metadata
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ObjectMetadata>
   */
	getObjectMetadata: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<ObjectMetadata>>;
  /**
   * Download object content
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<Blob>
   */
	downloadObjectContent: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<Blob>>;
  /**
   * Create or replace object content
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
   * @param body - Request body
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ObjectMetadata>
   */
	putObjectContent: (bucketName: string, objectKey: string, body: BodyInit, headers?: HeadersInit, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<ObjectMetadata>>;
  /**
   * Get object tags
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<TagsResponse>
   */
	getObjectTags: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<TagsResponse>>;
  /**
   * Replace object tags
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
   * @param body - Request body
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<TagsResponse>
   */
	putObjectTags: (bucketName: string, objectKey: string, body: TagsRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<TagsResponse>>;
  /**
   * List object versions
   *
   * @param bucketName - Bucket name.
   * @param objectKey - Full object key, URL encoded when used in the path.
   * @param query - Query parameters
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<ListVersionsResponse>
   */
	listObjectVersions: (bucketName: string, objectKey: string, query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<ListVersionsResponse>>;
  /**
   * Get bucket versioning status
   *
   * @param bucketName - Bucket name.
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<VersioningStatus>
   */
	getBucketVersioning: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<VersioningStatus>>;
  /**
   * Set bucket versioning status
   *
   * @param bucketName - Bucket name.
   * @param body - Request body
	 * @param options - Request options (signal, timeout, operationId)
   * @returns Promise resolving to FetchResponse<VersioningStatus>
   */
	setBucketVersioning: (bucketName: string, body: VersioningStatus, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }) => Promise<FetchResponse<VersioningStatus>>;
} {
  return {
		loginAdminSession: (body: AdminLoginRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<SuccessResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "loginAdminSession" };
	return client.post(`/admin/v1/auth/login`, body, undefined, finalOptions);
    },
		logoutAdminSession: (options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<SuccessResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "logoutAdminSession" };
	return client.post(`/admin/v1/auth/logout`, undefined, undefined, finalOptions);
    },
		getAdminSession: (options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<AdminSessionResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "getAdminSession" };
	return client.get(`/admin/v1/auth/session`, undefined, finalOptions);
    },
		createBucket: (body: CreateBucketRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<BucketDetails>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "createBucket" };
	return client.post(`/admin/v1/buckets`, body, undefined, finalOptions);
    },
		listBuckets: (query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<ListBucketsResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "listBuckets" };
      const queryString = query ? buildQueryParams(query) : '';
      const url = `/admin/v1/buckets` + (queryString ? '?' + queryString : '');
			return client.get(url, undefined, finalOptions);
    },
		deleteBucket: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<boolean>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "deleteBucket" };
	return client.del(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}`, undefined, finalOptions);
    },
		getBucket: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<BucketDetails>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "getBucket" };
	return client.get(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}`, undefined, finalOptions);
    },
		listObjects: (bucketName: string, query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<ListObjectsResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "listObjects" };
      const queryString = query ? buildQueryParams(query) : '';
      const url = `/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects` + (queryString ? '?' + queryString : '');
			return client.get(url, undefined, finalOptions);
    },
		deleteObject: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<boolean>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "deleteObject" };
	return client.del(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}`, undefined, finalOptions);
    },
		getObjectMetadata: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<ObjectMetadata>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "getObjectMetadata" };
	return client.get(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}`, undefined, finalOptions);
    },
		downloadObjectContent: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<Blob>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "downloadObjectContent" };
	return client.get(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}/content`, undefined, finalOptions);
    },
		putObjectContent: (bucketName: string, objectKey: string, body: BodyInit, headers?: HeadersInit, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<ObjectMetadata>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "putObjectContent" };
	return client.request<ObjectMetadata>(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}/content`, { method: "PUT", headers, body }, finalOptions);
    },
		getObjectTags: (bucketName: string, objectKey: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<TagsResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "getObjectTags" };
	return client.get(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}/tags`, undefined, finalOptions);
    },
		putObjectTags: (bucketName: string, objectKey: string, body: TagsRequest, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<TagsResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "putObjectTags" };
	return client.put(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}/tags`, body, undefined, finalOptions);
    },
		listObjectVersions: (bucketName: string, objectKey: string, query?: { next?: string; limit?: number; search?: string }, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<ListVersionsResponse>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "listObjectVersions" };
      const queryString = query ? buildQueryParams(query) : '';
      const url = `/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/objects/${encodeURIComponent(String(objectKey))}/versions` + (queryString ? '?' + queryString : '');
			return client.get(url, undefined, finalOptions);
    },
		getBucketVersioning: (bucketName: string, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<VersioningStatus>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "getBucketVersioning" };
	return client.get(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/versioning`, undefined, finalOptions);
    },
		setBucketVersioning: (bucketName: string, body: VersioningStatus, options?: { signal?: AbortSignal; timeout?: number; operationId?: string }): Promise<FetchResponse<VersioningStatus>> => {
		const finalOptions = { ...options, operationId: options?.operationId ?? "setBucketVersioning" };
	return client.put(`/admin/v1/buckets/${encodeURIComponent(String(bucketName))}/versioning`, body, undefined, finalOptions);
    }
  };
}

/** AdminLoginRequest schema */
export type AdminLoginRequest = { password: string; username: string };

/** AdminSessionResponse schema */
export type AdminSessionResponse = { mode: "open" | "session" | "basic"; username: string | null };

/** BucketDetails schema */
export type BucketDetails = BucketInfo;

/** BucketInfo schema */
export type BucketInfo = { created_at: string; name: string; versioning_enabled: boolean };

/** CreateBucketRequest schema */
export type CreateBucketRequest = { name: string };

/** ErrorResponse schema */
export type ErrorResponse = { code: string; details?: string | null; error: string };

/** ListBucketsResponse schema */
export type ListBucketsResponse = { items: Array<BucketInfo>; next: string | null };

/** ListObjectsResponse schema */
export type ListObjectsResponse = { items: Array<ObjectInfo>; next: string | null };

/** ListVersionsResponse schema */
export type ListVersionsResponse = { items: Array<ObjectVersionInfo>; next: string | null };

/** ObjectInfo schema */
export type ObjectInfo = { content_type: string | null; etag: string; key: string; last_modified: string; size: number; storage_class: string };

/** ObjectMetadata schema */
export type ObjectMetadata = { content_type: string | null; etag: string; key: string; last_modified: string; metadata: Record<string, string>; size: number; storage_class: string; version_id: string | null };

/** ObjectVersionInfo schema */
export type ObjectVersionInfo = { etag: string; is_latest: boolean; key: string; last_modified: string; size: number; version_id: string };

/** SuccessResponse schema */
export type SuccessResponse = { success: boolean };

/** TagsRequest schema */
export type TagsRequest = { tags: Record<string, string> };

/** TagsResponse schema */
export type TagsResponse = { tags: Record<string, string> };

/** VersioningStatus schema */
export type VersioningStatus = { enabled: boolean };

